FROM golang:alpine3.22 AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY loadbalancer/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o loadbalancer loadbalancer.go


FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root
COPY --from=build /app/loadbalancer .
EXPOSE 9080
CMD [ "./loadbalancer" ]
